version: "3"

services:
  idea-repository-plugin:
    image: nginx
    volumes:
      - ./content:/usr/share/nginx/html:ro
    ports:
      - 7887:80
    environment:
      NGNIX_HOST: ideaplugins.yazago.site
      NGNIX_PORT: 80
    restart: always
